### ISSUE TITLE
泄漏了。。

### ISSUE THREAD

**Issue by bachan111** [Jeremyzwc/WanAndroidAppKotlinMVVM#1]
![1662536429638](https://user-images.githubusercontent.com/85537846/188818651-494a272a-6f4f-443d-9e34-9cb3115e3084.png)

**Comment by Jeremyzwc** [comment]
> ![1662536429638](https://user-images.githubusercontent.com/85537846/188818651-494a272a-6f4f-443d-9e34-9cb3115e3084.png)


这个是ViewPager+Fragment使用导致的泄漏，我这处理一下提交

**Comment by Jeremyzwc** [comment]
> ![1662536429638](https://user-images.githubusercontent.com/85537846/188818651-494a272a-6f4f-443d-9e34-9cb3115e3084.png)

已经fix了
